remote_theme: daattali/beautiful-jekyll
title: Organ Mountain Digital
description: Community-powered media for Las Cruces
baseurl: ""
url: "https://organmountaindigital.com"
email: contact@organmountaindigital.com
repository: organmountaindigital/organmountaindigital.github.io

# Navigation
navbar-links:
  Home: /
  About: /about
  Events: /events
  Support: /support
  Impact: /impact
  "Veteran-Owned": /veteran

# Social
email: contact@organmountaindigital.com
locale: en-US

collections:
  events:
    output: true
    permalink: /events/:title/
  vetowned:
    output: true
    permalink: /vet-owned/:title/
