title: Organ Mountain Digital
description: Community-powered media for Las Cruces
baseurl: "" # leave this blank if deploying to a custom domain
url: "https://organmountaindigital.com"
theme: minima
markdown: kramdown

# Navigation links
theme_config:
  navigation:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Events"
      url: "/events/"
    - title: "Support Us"
      url: "/support/"
    - title: "Impact"
      url: "/impact/"
    - title: "Veteran-Owned"
      url: "/veteran/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
