remote_theme: daattali/beautiful-jekyll
inject_custom_head: true

title: Organ Mountain Digital
description: Community-powered media for Las Cruces
baseurl: ""
url: "https://organmountaindigital.com"
email: contact@organmountaindigital.com
locale: en-US

repository: organmountaindigital/organmountaindigital.github.io
