remote_theme: mmistakes/minimal-mistakes
title: Organ Mountain Digital
description: Community-powered media for Las Cruces
baseurl: ""
url: "https://organmountaindigital.com"
repository: organmountaindigital/organmountaindigital.github.io
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Build settings
defaults:
  - scope:
      path: ""
    values:
      layout: single

markdown: kramdown
highlighter: rouge

# Navigation
navigation:
  main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Events"
    url: /events/
  - title: "Support"
    url: /support/
  - title: "Impact"
    url: /impact/
  - title: "Veteran-Owned"
    url: /veteran/

# Social
email: contact@organmountaindigital.com
locale: en-US

collections:
  events:
    output: true
    permalink: /events/:title/
  vetowned:
    output: true
    permalink: /vet-owned/:title/
