remote_theme: mmistakes/minimal-mistakes
title: Organ Mountain Digital
description: Community-powered media for Las Cruces
baseurl: ""
url: "https://organmountaindigital.com"
repository: yourgithubusername/organmountaindigital
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Build settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

markdown: kramdown
highlighter: rouge

# Navigation
header_pages:
  - index.md
  - about.md
  - events.md
  - support.md
  - impact.md
  - veteran.md

# Social
email: contact@organmountaindigital.com
locale: en-US
